# HandWritten Image detection

In [1]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np

In [2]:
(X_train, Y_train), (X_test, Y_test) = keras.datasets.mnist.load_data()

In [3]:
X_train.shape

(60000, 28, 28)

In [4]:
x_train_flattened = X_train.reshape(60000, 28*28)

In [5]:
x_test_flattened = X_test.reshape(len(X_test), 28*28)

In [6]:
###scaling

In [7]:
x_train_flattened = x_train_flattened / 255

In [8]:
### creating the model

### model with no hidden layers

In [9]:
### simple model with no hidden layers
model = keras.Sequential([
    keras.layers.Dense(10, input_shape = (784,), activation = 'sigmoid')
]) ## 10 is the size of the output neuron and 784 is the input

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(x_train_flattened, Y_train, epochs=30)

Epoch 1/30
1875/1875 [==============================] - 8s 3ms/step - loss: 0.4684 - accuracy: 0.8765
Epoch 2/30
1875/1875 [==============================] - 6s 3ms/step - loss: 0.3037 - accuracy: 0.9155
Epoch 3/30
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2830 - accuracy: 0.9215
Epoch 4/30
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2734 - accuracy: 0.9233
Epoch 5/30
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2669 - accuracy: 0.9259
Epoch 6/30
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2617 - accuracy: 0.9273
Epoch 7/30
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2583 - accuracy: 0.9280
Epoch 8/30
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2555 - accuracy: 0.9291
Epoch 9/30
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2529 - accuracy: 0.9295
Epoch 10/30
1875/1875 [==============================] - 6s 3ms/step - loss: 0.251

In [10]:
### testing on test dataset

In [11]:
x_test = x_test_flattened / 255

In [12]:
model.evaluate(x_test, Y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.2775 - accuracy: 0.9284


[0.277521550655365, 0.9283999800682068]

In [13]:
y_predicts = model.predict(x_test)  ### gives output of the prediction of the input dataset

313/313 [==============================] - 1s 2ms/step


In [14]:
y_predicts_val = []
for i in y_predicts:
    y_predicts_val.append(np.argmax(i))

In [15]:
y_predicts_val[:7]    ### predicted values

[7, 2, 1, 0, 4, 1, 4]

In [16]:
Y_test[:7]    ### actual values

array([7, 2, 1, 0, 4, 1, 4], dtype=uint8)

In [17]:
### confusion matrix
cm = tf.math.confusion_matrix(labels=Y_test, predictions = y_predicts_val)
print(cm)

tf.Tensor(
[[ 962    0    0    2    1    6    5    3    1    0]
 [   0 1116    4    1    0    1    3    2    8    0]
 [   7   10  928   13    9    3   10   11   38    3]
 [   5    0   18  906    4   30    2   10   27    8]
 [   1    2    6    3  926    0    7    7    8   22]
 [  10    3    2   25    9  780   14    8   35    6]
 [  13    3    8    1    8   10  912    1    2    0]
 [   1   10   19    4    4    1    0  958    3   28]
 [   7   11    5   15   10   17    9   10  879   11]
 [  10    8    1    6   29    5    0   24    9  917]], shape=(10, 10), dtype=int32)


### model with 1 hidden layer

In [21]:

model1 = keras.Sequential([
    keras.layers.Dense(100, input_shape = (784,), activation = 'relu'),
    keras.layers.Dense(10, activation = tf.nn.sigmoid)
]) ## 10 is the size of the output neuron and 784 is the input

model1.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model1.fit(x_train_flattened, Y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 11s 5ms/step - loss: 0.2820 - accuracy: 0.9214
Epoch 2/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1294 - accuracy: 0.9627
Epoch 3/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0916 - accuracy: 0.9727
Epoch 4/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0709 - accuracy: 0.9782
Epoch 5/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0559 - accuracy: 0.9833


In [22]:
### evaluating
model1.evaluate(x_test, Y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0862 - accuracy: 0.9724


[0.08615786582231522, 0.9724000096321106]

### model with 2 hidden layers

In [27]:
model2 = keras.Sequential([
    keras.layers.Dense(50, input_shape = (784,), activation = 'relu'),
    keras.layers.Dense(50, activation = 'relu'),
    keras.layers.Dense(10, activation = 'softmax')
])

model2.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model2.fit(x_train_flattened, Y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 11s 5ms/step - loss: 0.2980 - accuracy: 0.9131
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1405 - accuracy: 0.9575
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1041 - accuracy: 0.9681
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0828 - accuracy: 0.9743
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0703 - accuracy: 0.9777


In [28]:
model2.evaluate(x_test, Y_test)

313/313 [==============================] - 2s 4ms/step - loss: 0.0939 - accuracy: 0.9713


[0.09390000998973846, 0.9713000059127808]

# Matrix excersize 

### excersize 1

In [31]:
revenue_in_usd = np.array([[200, 220, 250], [68, 79, 105], [110, 140, 180], [80, 85, 90]])
conversion_rate = 75

revenew_in_inr = revenue_in_usd * conversion_rate
revenew_in_inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

### excersize 2 

In [32]:
units_sold = np.array([[50, 60, 25], [10, 13, 5], [40, 70, 52]])
price_per_unit = np.array([20, 30, 15])

total_price_per_month = np.dot(price_per_unit, units_sold)
total_price_per_month

array([1900, 2640, 1430])

In [35]:
total_price_per_flower = np.dot(price_per_unit, units_sold.T)
total_price_per_flower

array([3175,  665, 3680])